export enum EventType {

    PLAY_CLICKED = "PLAY_CLICKED",
    PAUSE_CLICKED = "PAUSE_CLICKED",
    TOGGLE_CLICKED = "TOGGLE_CLICKED",

    VOLUME_CHANGED = "VOLUME_CHANGED",
    MUTE_CLICKED = "MUTE_CLICKED",
    UNMUTE_CLICKED = "UNMITE_CLICKED",

    FULLSCREEN_ENTER = "FULLSCREEN_ENTER",
    FULLSCREEN_EXIT = "FULLSCREEN_EXIT",

    GUI_SHOW = "GUI_SHOW",
    GUI_HIDE = "GUI_HIDE",
    GUI_INITIALIZED = "GUI_INITIALIZED",

    LIBRARY_CREATED = "LIBRARY_CREATED",
    LIBRARY_INITIALIZED = "LIBRARY_INITIALIZED",

    ERROR_DISPLAY = "ERROR_DISPLAY",

    TITLE_SETTED = "TITLE_SETTED",
    SUBTITLE_SETTED = "SUBTITLE_SETTED"

}