export enum EventType {
    PLAY_CLICKED = "PLAY_CLICKED",
    PAUSE_CLICKED = "PAUSE_CLICKED",

    VIDEO_PAUSED = "VIDEO_PAUSED",
    VIDEO_PLAYING = "VIDEO_PLAYING",

    VOLUME_CHANGED = "VOLUME_CHANGED",
    FULLSCREEN_ENTER = "FULLSCREEN_ENTER",
    FULLSCREEN_EXIT = "FULLSCREEN_EXIT",

    GUI_SHOW = "GUI_SHOW",
    GUI_HIDE = "GUI_HIDE",


}